import java.awt.Component;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

public class ManagerJFrame extends javax.swing.JFrame {

    public ManagerJFrame() {
        initComponents();
        loadCSV("C:\\Users\\USER\\Downloads\\Employee Details.csv");
    }

    // Load CSV data into JTable
    private void loadCSV(String filename) {
        String line;
        DefaultTableModel model = (DefaultTableModel) TBL1.getModel();

        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            // Read the CSV header
            line = br.readLine();
            String[] headers = line.split(",");

            // Set table headers
            model.setColumnIdentifiers(headers);

            // Read remaining lines
            while ((line = br.readLine()) != null) {
                String[] data = parseCSVLine(line); // Use parseCSVLine to handle commas within fields
                model.addRow(data);
            }

            // Adjust row heights
            adjustRowHeight();

            // Make table non-editable
            for (int i = 0; i < model.getColumnCount(); i++) {
                TableColumn column = TBL1.getColumnModel().getColumn(i);
                column.setCellEditor(null);
            }

            // Make table non-resizable
            TBL1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

            // Resize table columns to fit content
            for (int i = 0; i < model.getColumnCount(); i++) {
                TableColumn column = TBL1.getColumnModel().getColumn(i);
                int width = getColumnWidth(i);
                column.setPreferredWidth(width);
                column.setMaxWidth(width);
                column.setMinWidth(width);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Parse CSV line
    private String[] parseCSVLine(String line) {
        // Pattern to match fields enclosed in double quotes, allowing for commas within them
        Pattern pattern = Pattern.compile("\"([^\"]*)\"|(?<=,|^)([^,]*)(?:,|$)");

        Matcher matcher = pattern.matcher(line);
        List<String> fields = new ArrayList<>();
        while (matcher.find()) {
            String field = matcher.group(1); // Quoted value
            if (field == null) {
                field = matcher.group(2); // Unquoted value
            }
            fields.add(field);
        }

        return fields.toArray(String[]::new);
    }

    // Adjust row heights to fit content
    private void adjustRowHeight() {
        for (int row = 0; row < TBL1.getRowCount(); row++) {
            int rowHeight = TBL1.getRowHeight();
            for (int column = 0; column < TBL1.getColumnCount(); column++) {
                Component comp = TBL1.prepareRenderer(TBL1.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }
            TBL1.setRowHeight(row, rowHeight);
        }
    }

    // Get the preferred width of a column based on the content
    private int getColumnWidth(int column) {
        int width = 0;
        for (int row = 0; row < TBL1.getRowCount(); row++) {
            TableCellRenderer renderer = TBL1.getCellRenderer(row, column);
            Component comp = TBL1.prepareRenderer(renderer, row, column);
            width = Math.max(comp.getPreferredSize().width + TBL1.getIntercellSpacing().width, width);
        }
        return width;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN1 = new javax.swing.JPanel();
        LBL1 = new java.awt.Label();
        TB1 = new javax.swing.JTabbedPane();
        SCRP1 = new javax.swing.JScrollPane();
        TBL1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBL1.setAlignment(java.awt.Label.CENTER);
        LBL1.setBackground(new java.awt.Color(51, 51, 55));
        LBL1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LBL1.setForeground(new java.awt.Color(255, 255, 255));
        LBL1.setName("LBL1"); // NOI18N
        LBL1.setText("MANAGER PORTAL");

        TB1.setBackground(new java.awt.Color(51, 51, 55));
        TB1.setForeground(new java.awt.Color(255, 255, 255));
        TB1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        SCRP1.setToolTipText("");
        SCRP1.setAutoscrolls(true);

        TBL1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        SCRP1.setViewportView(TBL1);

        TB1.addTab("Employee Details", SCRP1);
        SCRP1.getAccessibleContext().setAccessibleParent(null);

        javax.swing.GroupLayout PN1Layout = new javax.swing.GroupLayout(PN1);
        PN1.setLayout(PN1Layout);
        PN1Layout.setHorizontalGroup(
            PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBL1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addComponent(TB1)
        );
        PN1Layout.setVerticalGroup(
            PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN1Layout.createSequentialGroup()
                .addComponent(LBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManagerJFrame().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label LBL1;
    private javax.swing.JPanel PN1;
    private javax.swing.JScrollPane SCRP1;
    private javax.swing.JTabbedPane TB1;
    private javax.swing.JTable TBL1;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
